odom_node:
    wheel_base: 0.39
    wheel_radius: 0.06858
    pulse_per_rev: 2443
camera_warp_node:
    src:
        - [105, 215]
        - [208, 215]
        - [120, 140]
        - [195, 145]
    dst:
        - [131, 215]
        - [182, 215]
        - [131, 149]
        - [182, 149]
